# Generated by Django 5.2.5 on 2025-09-03 20:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cargo', models.CharField(choices=[('GER', 'Gerente'), ('CORD', 'Coordenador'), ('SUP', 'Supervisor'), ('AUX', 'Auxiliar')], max_length=6)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Navio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boca', models.CharField(blank=True, max_length=50, null=True)),
                ('armador', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.CharField(blank=True, max_length=100, null=True)),
                ('lado', models.CharField(blank=True, max_length=50, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True, verbose_name='ETA')),
                ('pob', models.DateTimeField(blank=True, null=True, verbose_name='POB')),
                ('local_atracacao', models.CharField(blank=True, max_length=100, null=True)),
                ('inicio_operacao', models.DateTimeField(blank=True, null=True, verbose_name='Início Operação')),
                ('ternos', models.IntegerField(blank=True, null=True)),
                ('tempo_operacao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tempo de Operação (h)')),
                ('volume_descarga', models.TextField(blank=True, null=True)),
                ('clientes_descarga', models.TextField(blank=True, null=True)),
                ('volume_embarque', models.TextField(blank=True, null=True)),
                ('clientes_embarque', models.TextField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoVideoNavio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='navios/midias/')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('navio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='historico.navio')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoNavio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='navios/documentos/')),
                ('navio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='historico.navio')),
            ],
        ),
    ]
