# Generated by Django 5.2.5 on 2025-09-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navio',
            name='clientes_descarga',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='navio',
            name='clientes_embarque',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='navio',
            name='tempo_operacao',
            field=models.DurationField(blank=True, null=True, verbose_name='Tempo de Operação'),
        ),
        migrations.AlterField(
            model_name='navio',
            name='volume_descarga',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='navio',
            name='volume_embarque',
            field=models.CharField(blank=True, null=True),
        ),
    ]
