# Generated by Django 5.2.5 on 2025-09-05 02:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0002_alter_navio_clientes_descarga_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navio',
            old_name='lado',
            new_name='bordo',
        ),
        migrations.RenameField(
            model_name='navio',
            old_name='local_atracacao',
            new_name='navio',
        ),
        migrations.RenameField(
            model_name='navio',
            old_name='clientes_descarga',
            new_name='peso_descarga',
        ),
        migrations.RenameField(
            model_name='navio',
            old_name='clientes_embarque',
            new_name='peso_embarque',
        ),
        migrations.AddField(
            model_name='fotovideonavio',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotovideonavio',
            name='tipo_peca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navio',
            name='fim_operacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termino Operação'),
        ),
        migrations.AddField(
            model_name='navio',
            name='loa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
