# Generated by Django 5.2.5 on 2025-10-28 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0003_rename_lado_navio_bordo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotovideonavio',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='navios/midias/'),
        ),
        migrations.AlterField(
            model_name='fotovideonavio',
            name='navio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midias', to='historico.navio'),
        ),
        migrations.AlterField(
            model_name='navio',
            name='bordo',
            field=models.CharField(blank=True, choices=[('BB', 'Bombordo'), ('BE', 'Boreste')], max_length=50, null=True),
        ),
    ]
