# Generated by Django 5.2.5 on 2025-11-03 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0004_alter_fotovideonavio_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotovideonavio',
            name='navio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='historico.navio'),
        ),
    ]
